### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by mateusz-** [jue89/node-mqttsngw#1]
Hi,

Cool project, thanks for making it open source! Do you think it's ready for production use?

Thanks.

**Comment by jue89** [comment]
Hi,

this is actually used in production ;)

But it does not implement the whole spec, yet.

This are the features that are not supported atm:
 * Last will
 * Raw UDP (Only DTLS atm ...)
 * Gateway discovery (You have to know its IPv6 address or hostname)
 * Client asleep state
 * Pre-defined topics
 * Aggregating gateway (It just supports transparent gateway)

The code is prepared for these things but they haven't been required by the project, yet. Thus, they are still on the list to be implemented.

Does this help? Is there something missing for your use case?

Edit: The DTLS implementation compiles only up to Node 8. Node 10-compatibility is also pending - they switched from OpenSSL 1.0.2 to OpenSSL 1.1.0.

**Comment by mateusz-** [comment]
Sounds good, thanks @jue89.
